<template><MinipLayout title="个人资料" :canBack="true"><div class="avatar-card"><div class="avatar">{{ user.avatar || '👤' }}</div><button @click="alert('更换头像')">更换头像</button></div><div class="form"><div class="row"><span>昵称</span><input v-model="user.name" /></div><div class="row"><span>手机号</span><input v-model="user.phone" readonly /></div><div class="row"><span>邮箱</span><input v-model="user.email" placeholder="未设置" /></div><div class="row"><span>性别</span><select v-model="user.gender"><option>男</option><option>女</option><option>保密</option></select></div><div class="row"><span>生日</span><input v-model="user.birthday" type="date" /></div></div><button class="save-btn" @click="save">保存修改</button></MinipLayout></template>
<script setup>import { ref, onMounted } from 'vue'; import api from '@/api/request'; import { ElMessage } from 'element-plus'; import MinipLayout from './MinipLayout.vue'; const user = ref({ avatar: '👤', name: '', phone: '', email: '', gender: '保密', birthday: '' })
const loading = ref(false); onMounted(async () => { try {

  loading.value = true
  const r = await api.get('/users/me'); if (r.code === 0 && r.data) { user.value = { ...user.value, ...r.data }; if (user.value.name) user.value.avatar = user.value.name.charAt(0).toUpperCase() } } catch {}
  finally {
    loading.value = false
  } }); async function save() { try { await api.put('/users/me', user.value); ElMessage.success('保存成功') } catch { ElMessage.success('保存成功（演示模式）') } } </script>
<style scoped>.avatar-card { background: #fff; border-radius: 12px; padding: 20px; text-align: center; margin-bottom: 12px; } .avatar { width: 72px; height: 72px; border-radius: 50%; background: linear-gradient(135deg, #6366f1, #8b5cf6); color: #fff; display: inline-flex; align-items: center; justify-content: center; font-size: 32px; margin-bottom: 12px; } .avatar-card button { background: #eef2ff; color: #6366f1; border: 0; border-radius: 16px; padding: 6px 16px; font-size: 12px; cursor: pointer; } .form { background: #fff; border-radius: 12px; overflow: hidden; margin-bottom: 12px; } .row { display: flex; align-items: center; padding: 12px; gap: 12px; border-bottom: 1px solid #f5f6f8; font-size: 13px; } .row:last-child { border-bottom: 0; } .row span { color: #6b7280; width: 60px; flex-shrink: 0; } .row input, .row select { flex: 1; border: 0; outline: none; font-size: 13px; background: transparent; color: #1f2329; } .save-btn { width: 100%; background: #6366f1; color: #fff; border: 0; border-radius: 10px; padding: 12px; font-size: 14px; font-weight: 500; cursor: pointer; }</style>