-- 发票管理表
CREATE TABLE IF NOT EXISTS invoices (
  id INT PRIMARY KEY AUTO_INCREMENT,
  invoice_no VARCHAR(50) NOT NULL COMMENT '发票号码',
  invoice_code VARCHAR(50) COMMENT '发票代码',
  invoice_type ENUM('vat_special', 'vat_normal', 'receipt') NOT NULL COMMENT '发票类型：增值税专用发票/普通发票/收据',
  direction ENUM('input', 'output') NOT NULL COMMENT '进项/销项',
  invoice_date DATE NOT NULL COMMENT '开票日期',
  seller_name VARCHAR(200) NOT NULL COMMENT '销方名称',
  seller_tax_no VARCHAR(50) COMMENT '销方税号',
  buyer_name VARCHAR(200) NOT NULL COMMENT '购方名称',
  buyer_tax_no VARCHAR(50) COMMENT '购方税号',
  total_amount DECIMAL(15,2) NOT NULL COMMENT '价税合计',
  tax_amount DECIMAL(15,2) DEFAULT 0 COMMENT '税额',
  amount_without_tax DECIMAL(15,2) NOT NULL COMMENT '不含税金额',
  tax_rate DECIMAL(5,2) DEFAULT 0 COMMENT '税率(%)',
  image_path VARCHAR(500) COMMENT '发票图片路径',
  related_type ENUM('purchase', 'sale', 'none') DEFAULT 'none' COMMENT '关联类型',
  related_id INT COMMENT '关联业务单据ID',
  status ENUM('pending', 'verified', 'void') DEFAULT 'pending' COMMENT '状态：待核销/已核销/已作废',
  note TEXT COMMENT '备注',
  creator_id INT COMMENT '创建人ID',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_invoice_no (invoice_no),
  INDEX idx_invoice_date (invoice_date),
  INDEX idx_direction (direction),
  INDEX idx_related_type (related_type),
  INDEX idx_status (status),
  FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发票管理表';
