-- ============================================================
-- OA 流程引擎 · 种子数据 (P0 四流程 · 2026-09-08 · AutoClaw)
-- 来源: /root/jxy-os/hengqin-wanqu-minip/src/data/oa-flows.js (只读提取)
--   leave(请假) / reimburse(报销,金额网关+resubmitPolicy:restart)
--   seal(用印) / vehicle(用车)
-- 字段配置 form_config 与前端 f() 输出完全同构
-- ============================================================

INSERT INTO workflow_definitions
  (tenant_id, name, code, category, description, flow_config, form_config) -- version=1, is_active=1, created_by=NULL 走默认
VALUES
(1, '请假申请', 'leave', 'hr', '请假申请：额度校验 → 直属上级 → 按天数路由（≤3天归档 / ≤7天加部门负责人 / >7天加分管总监）',
'{"nodes":[{"id":"n1","type":"start","name":"员工","role":"applicant"},{"id":"n2","type":"gate","name":"额度网关","gateType":"quota","gateConfig":{"field":"leaveType","checkField":"days","max":{"事假":30,"病假":15,"年假":10,"调休":5,"婚假":10,"陪产假":15,"其他":3},"branches":[{"cond":"balance_insufficient","action":"reject","message":"余额不足，请改请事假"},{"cond":"else","nextNodeId":"n3"}]}},{"id":"n3","type":"approve","name":"直属上级","role":"direct_supervisor","timeout":24,"rejectTo":"n1"},{"id":"n4","type":"gate","name":"天数网关","gateType":"duration","gateConfig":{"field":"days","branches":[{"cond":"<=3","nextNodeIds":["n5"]},{"cond":"<=7","nextNodeIds":["n6"]},{"cond":">7","nextNodeIds":["n6","n7"]}]}},{"id":"n5","type":"end","name":"归档","actions":["deduct_quota","notify_hr"]},{"id":"n6","type":"approve","name":"部门负责人","role":"dept_head","timeout":24,"rejectTo":"n1"},{"id":"n7","type":"approve","name":"分管总监","role":"director","timeout":48,"rejectTo":"n1"},{"id":"n8","type":"cc","name":"HR","role":"hr"}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n6","to":"n5"},{"from":"n7","to":"n5"},{"from":"n5","to":"n8"}],"resubmitPolicy":"restart"}',
'[{"key":"leaveType","label":"请假类型","type":"select","required":true,"options":["事假","病假","年假","调休","婚假","陪产假","其他"]},{"key":"range","label":"请假时间","type":"daterange","required":true},{"key":"days","label":"时长（天）","type":"number","required":true,"unit":"天"},{"key":"reason","label":"事由","type":"textarea","required":true},{"key":"handover","label":"交接人","type":"person","required":false},{"key":"attach","label":"附件证明","type":"attach","required":false}'),

(1, '费用报销', 'reimburse', 'finance', '费用报销：金额路由（≤5000 直属上级 / >5000 部门总管）→ 财务复核 → 出纳付款 → 归档；打回后重走（restart）',
'{"nodes":[{"id":"n1","type":"start","name":"员工","role":"applicant"},{"id":"n2","type":"gate","name":"金额网关","gateType":"amount","gateConfig":{"field":"amount","branches":[{"cond":"<=5000","nextNodeId":"n3"},{"cond":">5000","nextNodeId":"n4"}]}},{"id":"n3","type":"approve","name":"直属上级","role":"direct_supervisor","timeout":24,"rejectTo":"n1"},{"id":"n4","type":"approve","name":"部门总管","role":"dept_head","timeout":24,"rejectTo":"n1"},{"id":"n5","type":"approve","name":"财务复核","role":"finance","timeout":24,"rejectTo":"n1"},{"id":"n6","type":"approve","name":"出纳付款","role":"cashier","timeout":24,"rejectTo":"n1"},{"id":"n7","type":"end","name":"归档","actions":["voucher"]},{"id":"n8","type":"cc","name":"申请人","role":"applicant"},{"id":"n9","type":"cc","name":"HR","role":"hr"}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3","branch":"<=5000"},{"from":"n2","to":"n4","branch":">5000"},{"from":"n3","to":"n5"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n8","to":"n9"}],"resubmitPolicy":"restart"}',
'[{"key":"type","label":"报销类型","type":"select","required":true,"options":["交通","餐饮","住宿","办公","差旅","其他"]},{"key":"amount","label":"金额","type":"money","required":true},{"key":"detail","label":"费用明细","type":"textarea","required":true},{"key":"invoice","label":"发票","type":"attach","required":true},{"key":"dept","label":"归属项目/部门","type":"dept","required":true},{"key":"pay","label":"付款方式","type":"select","required":true,"options":["对公转账","个人垫付","其他"]}'),

(1, '用印申请', 'seal', 'admin', '用印申请：经理 → 总监 两级',
'{"nodes":[{"id":"n1","type":"start","name":"申请人","role":"applicant"},{"id":"n2","type":"approve","name":"经理审批","role":"manager","timeout":24,"rejectTo":"n1"},{"id":"n3","type":"approve","name":"总监审批","role":"director","timeout":48,"rejectTo":"n1"},{"id":"n4","type":"end","name":"归档","actions":[]},{"id":"n5","type":"cc","name":"行政部","role":"hr"}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"}],"resubmitPolicy":"restart"}',
'[{"key":"reason","label":"用印事由","type":"textarea","required":true},{"key":"sealType","label":"印章类型","type":"select","required":true,"options":["公章","合同章","财务章","法人章","其他"]},{"key":"docName","label":"文件名称","type":"text","required":true},{"key":"count","label":"份数","type":"number","required":true},{"key":"user","label":"用印人","type":"person","required":true},{"key":"outside","label":"是否外带","type":"switch","required":false}'),

(1, '用车申请', 'vehicle', 'admin', '用车申请：经理单级审批',
'{"nodes":[{"id":"n1","type":"start","name":"申请人","role":"applicant"},{"id":"n2","type":"approve","name":"经理审批","role":"manager","timeout":24,"rejectTo":"n1"},{"id":"n3","type":"end","name":"归档","actions":[]}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"}],"resubmitPolicy":"restart"}',
'[{"key":"reason","label":"用车事由","type":"textarea","required":true},{"key":"route","label":"出发地→目的地","type":"text","required":true},{"key":"range","label":"起止时间","type":"timerange","required":true},{"key":"riders","label":"乘车人","type":"person","required":false},{"key":"carType","label":"车型要求","type":"select","required":false,"options":["轿车","商务车","货车"]}');
